name:                MUDNAD
version:             0.1.0.0
github:              "githubuser/MUDNAD"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: MUD game server written using Cloud Haskell using redis

dependencies:
- base >= 4.7 && < 5
- atomic-primops >= 0.8.2
- lens >= 4.16.1
- HDBC >= 2.4.0.2
- stm >= 2.4.4.1
- bytestring >= 0.10.8.1
- parallel >= 3.2.1.0
- async >= 2.1.1.1
- network >= 2.6.3.5
- websockets >= 0.10.0.0
- text >= 0.11.2.0
- hedis >= 0.10.1
- extra >= 1.6.5
- argon2 >= 1.3.0.1
- stm-containers >= 0.2.16
- transformers >= 0.5.5.0
- DRBG >= 0.5.5
- distributed-process
- network-transport-tcp
- binary >= 0.8.5.1
- containers >= 0.5.10.2
- distributed-process-simplelocalnet >= 0.2.3.3
- hashable >= 1.2.7.0
- network-transport >= 0.5.2
- vector >= 0.12.0.1

library:
  source-dirs: src

executables:
  MUDNAD-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    dependencies:
    - MUDNAD

tests:
  MUDNAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MUDNAD
